[package]
name = "gpx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xmlparser = "0.13.5"
float-cmp = "0.9.0"
plotters = "0.3.4"
roxmltree = "0.18.0"
